package data.io.user

import kotlinx.serialization.Serializable

/** user object of another use specific to our database */
@Serializable
data class NetworkItemIO(
    /** username of the current user */
    val displayName: String? = null,

    /** tag of the current user, unique in combination with [displayName]  */
    val tag: String? = null,

    /** current user's public id, generated by our BE - not associated with Firebase */
    val publicId: String? = null,

    /** url of a photo of the current user, derived from FirebaseUser object */
    val photoUrl: String? = null,

    /** Whether the user is a mutually included */
    val isMutual: Boolean? = null,

    /**
     * A decimal range between -1 and 10. -1 means blocked, 1 is muted,
     *  or just a far social circle, and 10 is the closest
     */
    val proximity: Float? = null
)