package data.io.user

import androidx.room.Ignore
import base.utils.toSha256
import data.io.social.UserConfiguration
import kotlinx.serialization.Serializable
import net.folivo.trixnity.core.model.UserId

/** user object specific to our database saved in custom DB */
@Serializable
data class UserIO(
    /** username of the current user */
    val displayName: String? = null,

    /** current idToken which should be active and can be associated with data in Cloud Identity */
    val idToken: String? = null,

    /** current session token of the Matrix protocol */
    val accessToken: String? = null,

    /** Matrix homeserver associated with this user */
    val matrixHomeserver: String? = null,

    /** Matrix user identifier */
    val matrixUserId: String? = null,

    /** current user's public id, generated by our BE - not associated with Firebase */
    val publicId: String? = null,

    /** current configuration specific to this user */
    val configuration: UserConfiguration? = null
) {
    val tag: String?
        @Ignore
        get() = matrixUserId?.let { UserId(it).generateUserTag() }

    val matrixDisplayName: String?
        @Ignore
        get() = if(matrixUserId != null) {
            UserId(matrixUserId).localpart
        }else null

    val isFullyValid: Boolean
        @Ignore
        get() = idToken != null
                && accessToken != null
                && matrixHomeserver != null
                && matrixUserId != null

    fun update(other: UserIO?): UserIO {
        return this.copy(
            displayName = other?.displayName ?: this.displayName,
            idToken = other?.idToken ?: this.idToken,
            accessToken = other?.accessToken ?: this.accessToken,
            matrixUserId = other?.matrixUserId ?: this.matrixUserId,
            matrixHomeserver = other?.matrixHomeserver ?: this.matrixHomeserver,
            publicId = other?.publicId ?: this.publicId,
            configuration = other?.configuration ?: this.configuration
        )
    }

    override fun toString(): String {
        return "{" +
                "displayName: $displayName, " +
                "idToken: $idToken, " +
                "accessToken: $accessToken, " +
                "matrixHomeserver: $matrixHomeserver, " +
                "matrixUserId: $matrixUserId, " +
                "publicId: $publicId, " +
                "configuration: $configuration" +
                "isFullyValid: $isFullyValid" +
                "}"
    }

    companion object {
        fun UserId.generateUserTag() = localpart.toSha256().take(6)

        fun initialsOf(displayName: String?): String {
            return displayName?.trim()
                ?.split("""[\s_\-.]+""".toRegex()) // split on space, underscore, hyphen, or dot
                ?.let {
                    when {
                        it.size >= 2 -> it[0].take(1) + it[1].take(1)
                        it.isNotEmpty() -> it[0].take(1)
                        else -> ""
                    }
                } ?: ""
        }
    }
}
