source 'https://cdn.cocoapods.org'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '15.3'
  # Pods for iosApp
	pod 'ComposeApp', :path => '../composeApp'
	pod 'FirebaseCore'
  	pod 'FirebaseAuth'
  	pod 'GoogleSignIn'
	pod 'FirebaseMessaging'

	target 'NotificationService' do
        	inherit! :search_paths
    	end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end