package base.global.verification

val emojisWithTranslation = mapOf(
    0 to Pair(
        "🐶",
        mapOf(
            "en" to "Dog",
            "ar" to "كَلب",
            "bg" to "Куче",
            "ca" to "Gos",
            "cs" to "Pes",
            "de" to "Hund",
            "eo" to "Hundo",
            "es" to "Perro",
            "et" to "Koer",
            "fi" to "Koira",
            "fr" to "Chien",
            "hr" to "pas",
            "hu" to "Kutya",
            "id" to "Anjing",
            "it" to "Cane",
            "ja" to "犬",
            "nb_NO" to "Hund",
            "nl" to "Hond",
            "pt_BR" to "Cachorro",
            "ru" to "Собака",
            "si" to "බල්ලා",
            "sk" to "Hlava psa",
            "sq" to "Qen",
            "sr" to "пас",
            "sv" to "Hund",
            "szl" to "null",
            "tzm" to "Aydi",
            "uk" to "Пес",
            "vi" to "Chó",
            "zh_Hans" to "狗"
        )
    ),
    1 to Pair(
        "🐱",
        mapOf(
            "en" to "Cat",
            "ar" to "هِرَّة",
            "bg" to "Котка",
            "ca" to "Gat",
            "cs" to "Kočka",
            "de" to "Katze",
            "eo" to "Kato",
            "es" to "Gato",
            "et" to "Kass",
            "fi" to "Kissa",
            "fr" to "Chat",
            "hr" to "mačka",
            "hu" to "Macska",
            "id" to "Kucing",
            "it" to "Gatto",
            "ja" to "猫",
            "nb_NO" to "Katt",
            "nl" to "Kat",
            "pt_BR" to "Gato",
            "ru" to "Кошка",
            "si" to "පූසා",
            "sk" to "Hlava mačky",
            "sq" to "Mace",
            "sr" to "мачка",
            "sv" to "Katt",
            "szl" to "null",
            "tzm" to "Amuc",
            "uk" to "Кіт",
            "vi" to "Mèo",
            "zh_Hans" to "猫"
        )
    ),
    2 to Pair(
        "🦁",
        mapOf(
            "en" to "Lion",
            "ar" to "أَسَد",
            "bg" to "Лъв",
            "ca" to "Lleó",
            "cs" to "Lev",
            "de" to "Löwe",
            "eo" to "Leono",
            "es" to "León",
            "et" to "Lõvi",
            "fi" to "Leijona",
            "fr" to "Lion",
            "hr" to "lav",
            "hu" to "Oroszlán",
            "id" to "Singa",
            "it" to "Leone",
            "ja" to "ライオン",
            "nb_NO" to "Løve",
            "nl" to "Leeuw",
            "pt_BR" to "Leão",
            "ru" to "Лев",
            "si" to "සිංහයා",
            "sk" to "Hlava leva",
            "sq" to "Luan",
            "sr" to "лав",
            "sv" to "Lejon",
            "szl" to "null",
            "tzm" to "Izem",
            "uk" to "Лев",
            "vi" to "Sư tử",
            "zh_Hans" to "狮子"
        )
    ),
    3 to Pair(
        "🐎",
        mapOf(
            "en" to "Horse",
            "ar" to "حِصَان",
            "bg" to "Кон",
            "ca" to "Cavall",
            "cs" to "Kůň",
            "de" to "Pferd",
            "eo" to "Ĉevalo",
            "es" to "Caballo",
            "et" to "Hobune",
            "fi" to "Hevonen",
            "fr" to "Cheval",
            "hr" to "konj",
            "hu" to "Ló",
            "id" to "Kuda",
            "it" to "Cavallo",
            "ja" to "馬",
            "nb_NO" to "Hest",
            "nl" to "Paard",
            "pt_BR" to "Cavalo",
            "ru" to "Лошадь",
            "si" to "අශ්වයා",
            "sk" to "Kôň",
            "sq" to "Kalë",
            "sr" to "коњ",
            "sv" to "Häst",
            "szl" to "null",
            "tzm" to "Ayyis",
            "uk" to "Кінь",
            "vi" to "Ngựa",
            "zh_Hans" to "马"
        )
    ),
    4 to Pair(
        "🦄",
        mapOf(
            "en" to "Unicorn",
            "ar" to "حِصَانٌ بِقَرن",
            "bg" to "Еднорог",
            "ca" to "Unicorn",
            "cs" to "Jednorožec",
            "de" to "Einhorn",
            "eo" to "Unukorno",
            "es" to "Unicornio",
            "et" to "Ükssarvik",
            "fi" to "Yksisarvinen",
            "fr" to "Licorne",
            "hr" to "jednorog",
            "hu" to "Egyszarvú",
            "id" to "Unicorn",
            "it" to "Unicorno",
            "ja" to "ユニコーン",
            "nb_NO" to "Enhjørning",
            "nl" to "Eenhoorn",
            "pt_BR" to "Unicórnio",
            "ru" to "Единорог",
            "si" to "null",
            "sk" to "Hlava jednorožca",
            "sq" to "Njëbrirësh",
            "sr" to "једнорог",
            "sv" to "Enhörning",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Єдиноріг",
            "vi" to "Kỳ lân",
            "zh_Hans" to "独角兽"
        )
    ),
    5 to Pair(
        "🐷",
        mapOf(
            "en" to "Pig",
            "ar" to "خِنزِير",
            "bg" to "Прасе",
            "ca" to "Porc",
            "cs" to "Prase",
            "de" to "Schwein",
            "eo" to "Porko",
            "es" to "Cerdo",
            "et" to "Siga",
            "fi" to "Sika",
            "fr" to "Cochon",
            "hr" to "svinja",
            "hu" to "Malac",
            "id" to "Babi",
            "it" to "Maiale",
            "ja" to "ブタ",
            "nb_NO" to "Gris",
            "nl" to "Varken",
            "pt_BR" to "Porco",
            "ru" to "Свинья",
            "si" to "null",
            "sk" to "Hlava prasaťa",
            "sq" to "Derr",
            "sr" to "прасе",
            "sv" to "Gris",
            "szl" to "null",
            "tzm" to "Ilef",
            "uk" to "Свиня",
            "vi" to "Heo",
            "zh_Hans" to "猪"
        )
    ),
    6 to Pair(
        "🐘",
        mapOf(
            "en" to "Elephant",
            "ar" to "فِيل",
            "bg" to "Слон",
            "ca" to "Elefant",
            "cs" to "Slon",
            "de" to "Elefant",
            "eo" to "Elefanto",
            "es" to "Elefante",
            "et" to "Elevant",
            "fi" to "Norsu",
            "fr" to "Éléphant",
            "hr" to "slon",
            "hu" to "Elefánt",
            "id" to "Gajah",
            "it" to "Elefante",
            "ja" to "ゾウ",
            "nb_NO" to "Elefant",
            "nl" to "Olifant",
            "pt_BR" to "Elefante",
            "ru" to "Слон",
            "si" to "null",
            "sk" to "Slon",
            "sq" to "Elefant",
            "sr" to "слон",
            "sv" to "Elefant",
            "szl" to "null",
            "tzm" to "Ilu",
            "uk" to "Слон",
            "vi" to "Voi",
            "zh_Hans" to "大象"
        )
    ),
    7 to Pair(
        "🐰",
        mapOf(
            "en" to "Rabbit",
            "ar" to "أَرنَب",
            "bg" to "Заек",
            "ca" to "Conill",
            "cs" to "Králík",
            "de" to "Hase",
            "eo" to "Kuniklo",
            "es" to "Conejo",
            "et" to "Jänes",
            "fi" to "Kani",
            "fr" to "Lapin",
            "hr" to "zec",
            "hu" to "Nyúl",
            "id" to "Kelinci",
            "it" to "Coniglio",
            "ja" to "うさぎ",
            "nb_NO" to "Kanin",
            "nl" to "Konijn",
            "pt_BR" to "Coelho",
            "ru" to "Кролик",
            "si" to "null",
            "sk" to "Hlava zajaca",
            "sq" to "Lepur",
            "sr" to "зец",
            "sv" to "Kanin",
            "szl" to "null",
            "tzm" to "Agnin",
            "uk" to "Кріль",
            "vi" to "Thỏ",
            "zh_Hans" to "兔子"
        )
    ),
    8 to Pair(
        "🐼",
        mapOf(
            "en" to "Panda",
            "ar" to "باندَا",
            "bg" to "Панда",
            "ca" to "Panda",
            "cs" to "Panda",
            "de" to "Panda",
            "eo" to "Pando",
            "es" to "Panda",
            "et" to "Panda",
            "fi" to "Panda",
            "fr" to "Panda",
            "hr" to "panda",
            "hu" to "Panda",
            "id" to "Panda",
            "it" to "Panda",
            "ja" to "パンダ",
            "nb_NO" to "Panda",
            "nl" to "Panda",
            "pt_BR" to "Panda",
            "ru" to "Панда",
            "si" to "null",
            "sk" to "Hlava pandy",
            "sq" to "Panda",
            "sr" to "панда",
            "sv" to "Panda",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Панда",
            "vi" to "Gấu trúc",
            "zh_Hans" to "熊猫"
        )
    ),
    9 to Pair(
        "🐓",
        mapOf(
            "en" to "Rooster",
            "ar" to "دِيك",
            "bg" to "Петел",
            "ca" to "Gall",
            "cs" to "Kohout",
            "de" to "Hahn",
            "eo" to "Virkoko",
            "es" to "Gallo",
            "et" to "Kukk",
            "fi" to "Kukko",
            "fr" to "Coq",
            "hr" to "kokot",
            "hu" to "Kakas",
            "id" to "Ayam",
            "it" to "Gallo",
            "ja" to "ニワトリ",
            "nb_NO" to "Hane",
            "nl" to "Haan",
            "pt_BR" to "Galo",
            "ru" to "Петух",
            "si" to "null",
            "sk" to "Kohút",
            "sq" to "Këndes",
            "sr" to "петао",
            "sv" to "Tupp",
            "szl" to "null",
            "tzm" to "Ayaẓiḍ",
            "uk" to "Когут",
            "vi" to "Gà trống",
            "zh_Hans" to "公鸡"
        )
    ),
    10 to Pair(
        "🐧",
        mapOf(
            "en" to "Penguin",
            "ar" to "بِطريق",
            "bg" to "Пингвин",
            "ca" to "Pingüí",
            "cs" to "Tučňák",
            "de" to "Pinguin",
            "eo" to "Pingveno",
            "es" to "Pingüino",
            "et" to "Pingviin",
            "fi" to "Pingviini",
            "fr" to "Manchot",
            "hr" to "pingvin",
            "hu" to "Pingvin",
            "id" to "Penguin",
            "it" to "Pinguino",
            "ja" to "ペンギン",
            "nb_NO" to "Pingvin",
            "nl" to "Pinguïn",
            "pt_BR" to "Pinguim",
            "ru" to "Пингвин",
            "si" to "null",
            "sk" to "Tučniak",
            "sq" to "Pinguin",
            "sr" to "пингвин",
            "sv" to "Pingvin",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Пінгвін",
            "vi" to "Chim cánh cụt",
            "zh_Hans" to "企鹅"
        )
    ),
    11 to Pair(
        "🐢",
        mapOf(
            "en" to "Turtle",
            "ar" to "سُلحفاة",
            "bg" to "Костенурка",
            "ca" to "Tortuga",
            "cs" to "Želva",
            "de" to "Schildkröte",
            "eo" to "Testudo",
            "es" to "Tortuga",
            "et" to "Kilpkonn",
            "fi" to "Kilpikonna",
            "fr" to "Tortue",
            "hr" to "kornjača",
            "hu" to "Teknős",
            "id" to "Kura-Kura",
            "it" to "Tartaruga",
            "ja" to "亀",
            "nb_NO" to "Skilpadde",
            "nl" to "Schildpad",
            "pt_BR" to "Tartaruga",
            "ru" to "Черепаха",
            "si" to "null",
            "sk" to "Korytnačka",
            "sq" to "Breshkë",
            "sr" to "корњача",
            "sv" to "Sköldpadda",
            "szl" to "null",
            "tzm" to "Ifker",
            "uk" to "Черепаха",
            "vi" to "Rùa",
            "zh_Hans" to "乌龟"
        )
    ),
    12 to Pair(
        "🐟",
        mapOf(
            "en" to "Fish",
            "ar" to "سَمَكَة",
            "bg" to "Риба",
            "ca" to "Peix",
            "cs" to "Ryba",
            "de" to "Fisch",
            "eo" to "Fiŝo",
            "es" to "Pez",
            "et" to "Kala",
            "fi" to "Kala",
            "fr" to "Poisson",
            "hr" to "riba",
            "hu" to "Hal",
            "id" to "Ikan",
            "it" to "Pesce",
            "ja" to "魚",
            "nb_NO" to "Fisk",
            "nl" to "Vis",
            "pt_BR" to "Peixe",
            "ru" to "Рыба",
            "si" to "null",
            "sk" to "Ryba",
            "sq" to "Peshk",
            "sr" to "риба",
            "sv" to "Fisk",
            "szl" to "null",
            "tzm" to "Aselm",
            "uk" to "Риба",
            "vi" to "Cá",
            "zh_Hans" to "鱼"
        )
    ),
    13 to Pair(
        "🐙",
        mapOf(
            "en" to "Octopus",
            "ar" to "أُخطُبُوط",
            "bg" to "Октопод",
            "ca" to "Pop",
            "cs" to "Chobotnice",
            "de" to "Oktopus",
            "eo" to "Polpo",
            "es" to "Pulpo",
            "et" to "Kaheksajalg",
            "fi" to "Tursas",
            "fr" to "Poulpe",
            "hr" to "hobotnica",
            "hu" to "Polip",
            "id" to "Gurita",
            "it" to "Polpo",
            "ja" to "たこ",
            "nb_NO" to "Blekksprut",
            "nl" to "Octopus",
            "pt_BR" to "Polvo",
            "ru" to "Осьминог",
            "si" to "null",
            "sk" to "Chobotnica",
            "sq" to "Oktapod",
            "sr" to "октопод",
            "sv" to "Bläckfisk",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Восьминіг",
            "vi" to "Bạch tuộc",
            "zh_Hans" to "章鱼"
        )
    ),
    14 to Pair(
        "🦋",
        mapOf(
            "en" to "Butterfly",
            "ar" to "فَرَاشَة",
            "bg" to "Пеперуда",
            "ca" to "Papallona",
            "cs" to "Motýl",
            "de" to "Schmetterling",
            "eo" to "Papilio",
            "es" to "Mariposa",
            "et" to "Liblikas",
            "fi" to "Perhonen",
            "fr" to "Papillon",
            "hr" to "leptir",
            "hu" to "Pillangó",
            "id" to "Kupu-Kupu",
            "it" to "Farfalla",
            "ja" to "ちょうちょ",
            "nb_NO" to "Sommerfugl",
            "nl" to "Vlinder",
            "pt_BR" to "Borboleta",
            "ru" to "Бабочка",
            "si" to "null",
            "sk" to "Motýľ",
            "sq" to "Flutur",
            "sr" to "лептир",
            "sv" to "Fjäril",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Метелик",
            "vi" to "Bướm",
            "zh_Hans" to "蝴蝶"
        )
    ),
    15 to Pair(
        "🌷",
        mapOf(
            "en" to "Flower",
            "ar" to "زَهرَة",
            "bg" to "Цвете",
            "ca" to "Flor",
            "cs" to "Květina",
            "de" to "Blume",
            "eo" to "Floro",
            "es" to "Flor",
            "et" to "Lill",
            "fi" to "Kukka",
            "fr" to "Fleur",
            "hr" to "svijet",
            "hu" to "Virág",
            "id" to "Bunga",
            "it" to "Fiore",
            "ja" to "花",
            "nb_NO" to "Blomst",
            "nl" to "Bloem",
            "pt_BR" to "Flor",
            "ru" to "Цветок",
            "si" to "null",
            "sk" to "Tulipán",
            "sq" to "Lule",
            "sr" to "цвет",
            "sv" to "Blomma",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Квітка",
            "vi" to "Hoa",
            "zh_Hans" to "花"
        )
    ),
    16 to Pair(
        "🌳",
        mapOf(
            "en" to "Tree",
            "ar" to "شَجَرَة",
            "bg" to "Дърво",
            "ca" to "Arbre",
            "cs" to "Strom",
            "de" to "Baum",
            "eo" to "Arbo",
            "es" to "Árbol",
            "et" to "Puu",
            "fi" to "Puu",
            "fr" to "Arbre",
            "hr" to "drvo",
            "hu" to "Fa",
            "id" to "Pohon",
            "it" to "Albero",
            "ja" to "木",
            "nb_NO" to "Tre",
            "nl" to "Boom",
            "pt_BR" to "Árvore",
            "ru" to "Дерево",
            "si" to "null",
            "sk" to "Listnatý strom",
            "sq" to "Pemë",
            "sr" to "дрво",
            "sv" to "Träd",
            "szl" to "null",
            "tzm" to "Aseklu",
            "uk" to "Дерево",
            "vi" to "Cây",
            "zh_Hans" to "树"
        )
    ),
    17 to Pair(
        "🌵",
        mapOf(
            "en" to "Cactus",
            "ar" to "صبار",
            "bg" to "Кактус",
            "ca" to "Cactus",
            "cs" to "Kaktus",
            "de" to "Kaktus",
            "eo" to "Kakto",
            "es" to "Cactus",
            "et" to "Kaktus",
            "fi" to "Kaktus",
            "fr" to "Cactus",
            "hr" to "kaktus",
            "hu" to "Kaktusz",
            "id" to "Kaktus",
            "it" to "Cactus",
            "ja" to "サボテン",
            "nb_NO" to "Kaktus",
            "nl" to "Cactus",
            "pt_BR" to "Cacto",
            "ru" to "Кактус",
            "si" to "null",
            "sk" to "Kaktus",
            "sq" to "Kaktus",
            "sr" to "кактус",
            "sv" to "Kaktus",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Кактус",
            "vi" to "Xương rồng",
            "zh_Hans" to "仙人掌"
        )
    ),
    18 to Pair(
        "🍄",
        mapOf(
            "en" to "Mushroom",
            "ar" to "فُطر",
            "bg" to "Гъба",
            "ca" to "Bolet",
            "cs" to "Houba",
            "de" to "Pilz",
            "eo" to "Fungo",
            "es" to "Seta",
            "et" to "Seen",
            "fi" to "Sieni",
            "fr" to "Champignon",
            "hr" to "gljiva",
            "hu" to "Gomba",
            "id" to "Jamur",
            "it" to "Fungo",
            "ja" to "きのこ",
            "nb_NO" to "Sopp",
            "nl" to "Paddenstoel",
            "pt_BR" to "Cogumelo",
            "ru" to "Гриб",
            "si" to "null",
            "sk" to "Huba",
            "sq" to "Kërpudhë",
            "sr" to "печурка",
            "sv" to "Svamp",
            "szl" to "null",
            "tzm" to "Agursel",
            "uk" to "Гриб",
            "vi" to "Nấm",
            "zh_Hans" to "蘑菇"
        )
    ),
    19 to Pair(
        "🌏",
        mapOf(
            "en" to "Globe",
            "ar" to "كُرَةٌ أرضِيَّة",
            "bg" to "Глобус",
            "ca" to "Globus terraqüi",
            "cs" to "Zeměkoule",
            "de" to "Globus",
            "eo" to "Globo",
            "es" to "Globo",
            "et" to "Maakera",
            "fi" to "Maapallo",
            "fr" to "Globe",
            "hr" to "Globus",
            "hu" to "Földgömb",
            "id" to "Bola Dunia",
            "it" to "Globo",
            "ja" to "地球",
            "nb_NO" to "Globus",
            "nl" to "Wereldbol",
            "pt_BR" to "Globo",
            "ru" to "Глобус",
            "si" to "null",
            "sk" to "Zemeguľa",
            "sq" to "Rruzull",
            "sr" to "глобус",
            "sv" to "Jordklot",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Глобус",
            "vi" to "Địa cầu",
            "zh_Hans" to "地球"
        )
    ),
    20 to Pair(
        "🌙",
        mapOf(
            "en" to "Moon",
            "ar" to "قَمَر",
            "bg" to "Луна",
            "ca" to "Lluna",
            "cs" to "Měsíc",
            "de" to "Mond",
            "eo" to "Luno",
            "es" to "Luna",
            "et" to "Kuu",
            "fi" to "Kuu",
            "fr" to "Lune",
            "hr" to "mjesec",
            "hu" to "Hold",
            "id" to "Bulan",
            "it" to "Luna",
            "ja" to "月",
            "nb_NO" to "Måne",
            "nl" to "Maan",
            "pt_BR" to "Lua",
            "ru" to "Луна",
            "si" to "null",
            "sk" to "Polmesiac",
            "sq" to "Hënë",
            "sr" to "месец",
            "sv" to "Måne",
            "szl" to "null",
            "tzm" to "Ayyur",
            "uk" to "Місяць",
            "vi" to "Mặt trăng",
            "zh_Hans" to "月亮"
        )
    ),
    21 to Pair(
        "☁️",
        mapOf(
            "en" to "Cloud",
            "ar" to "سَحابَة",
            "bg" to "Облак",
            "ca" to "Núvol",
            "cs" to "Mrak",
            "de" to "Wolke",
            "eo" to "Nubo",
            "es" to "Nube",
            "et" to "Pilv",
            "fi" to "Pilvi",
            "fr" to "Nuage",
            "hr" to "oblak",
            "hu" to "Felhő",
            "id" to "Awan",
            "it" to "Nuvola",
            "ja" to "雲",
            "nb_NO" to "Sky",
            "nl" to "Wolk",
            "pt_BR" to "Nuvem",
            "ru" to "Облако",
            "si" to "null",
            "sk" to "Oblak",
            "sq" to "Re",
            "sr" to "облак",
            "sv" to "Moln",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Хмара",
            "vi" to "Mây",
            "zh_Hans" to "云"
        )
    ),
    22 to Pair(
        "🔥",
        mapOf(
            "en" to "Fire",
            "ar" to "نار",
            "bg" to "Огън",
            "ca" to "Foc",
            "cs" to "Oheň",
            "de" to "Feuer",
            "eo" to "Fajro",
            "es" to "Fuego",
            "et" to "Tuli",
            "fi" to "Tuli",
            "fr" to "Feu",
            "hr" to "vatra",
            "hu" to "Tűz",
            "id" to "Api",
            "it" to "Fuoco",
            "ja" to "炎",
            "nb_NO" to "Flamme",
            "nl" to "Vuur",
            "pt_BR" to "Fogo",
            "ru" to "Огонь",
            "si" to "null",
            "sk" to "Oheň",
            "sq" to "Zjarr",
            "sr" to "ватра",
            "sv" to "Eld",
            "szl" to "null",
            "tzm" to "Timessi",
            "uk" to "Вогонь",
            "vi" to "Lửa",
            "zh_Hans" to "火"
        )
    ),
    23 to Pair(
        "🍌",
        mapOf(
            "en" to "Banana",
            "ar" to "مَوزَة",
            "bg" to "Банан",
            "ca" to "Plàtan",
            "cs" to "Banán",
            "de" to "Banane",
            "eo" to "Banano",
            "es" to "Plátano",
            "et" to "Banaan",
            "fi" to "Banaani",
            "fr" to "Banane",
            "hr" to "banana",
            "hu" to "Banán",
            "id" to "Pisang",
            "it" to "Banana",
            "ja" to "バナナ",
            "nb_NO" to "Banan",
            "nl" to "Banaan",
            "pt_BR" to "Banana",
            "ru" to "Банан",
            "si" to "null",
            "sk" to "Banán",
            "sq" to "Banane",
            "sr" to "банана",
            "sv" to "Banan",
            "szl" to "null",
            "tzm" to "Tabanant",
            "uk" to "Банан",
            "vi" to "Chuối",
            "zh_Hans" to "香蕉"
        )
    ),
    24 to Pair(
        "🍎",
        mapOf(
            "en" to "Apple",
            "ar" to "تُفَّاحَة",
            "bg" to "Ябълка",
            "ca" to "Poma",
            "cs" to "Jablko",
            "de" to "Apfel",
            "eo" to "Pomo",
            "es" to "Manzana",
            "et" to "Õun",
            "fi" to "Omena",
            "fr" to "Pomme",
            "hr" to "jabuka",
            "hu" to "Alma",
            "id" to "Apel",
            "it" to "Mela",
            "ja" to "リンゴ",
            "nb_NO" to "Eple",
            "nl" to "Appel",
            "pt_BR" to "Maçã",
            "ru" to "Яблоко",
            "si" to "null",
            "sk" to "Červené jablko",
            "sq" to "Mollë",
            "sr" to "јабука",
            "sv" to "Äpple",
            "szl" to "null",
            "tzm" to "Tadeffuyt",
            "uk" to "Яблуко",
            "vi" to "Táo",
            "zh_Hans" to "苹果"
        )
    ),
    25 to Pair(
        "🍓",
        mapOf(
            "en" to "Strawberry",
            "ar" to "فَراوِلَة",
            "bg" to "Ягода",
            "ca" to "Maduixa",
            "cs" to "Jahoda",
            "de" to "Erdbeere",
            "eo" to "Frago",
            "es" to "Fresa",
            "et" to "Maasikas",
            "fi" to "Mansikka",
            "fr" to "Fraise",
            "hr" to "jagoda",
            "hu" to "Eper",
            "id" to "Stroberi",
            "it" to "Fragola",
            "ja" to "いちご",
            "nb_NO" to "Jordbær",
            "nl" to "Aardbei",
            "pt_BR" to "Morango",
            "ru" to "Клубника",
            "si" to "null",
            "sk" to "Jahoda",
            "sq" to "Luleshtrydhe",
            "sr" to "јагода",
            "sv" to "Jordgubbe",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Полуниця",
            "vi" to "Dâu tây",
            "zh_Hans" to "草莓"
        )
    ),
    26 to Pair(
        "🌽",
        mapOf(
            "en" to "Corn",
            "ar" to "ذُرَة",
            "bg" to "Царевица",
            "ca" to "Blat de moro",
            "cs" to "Kukuřice",
            "de" to "Mais",
            "eo" to "Maizo",
            "es" to "Maíz",
            "et" to "Mais",
            "fi" to "Maissi",
            "fr" to "Maïs",
            "hr" to "kukuruza",
            "hu" to "Kukorica",
            "id" to "Jagung",
            "it" to "Mais",
            "ja" to "とうもろこし",
            "nb_NO" to "Mais",
            "nl" to "Maïs",
            "pt_BR" to "Milho",
            "ru" to "Кукуруза",
            "si" to "null",
            "sk" to "Kukuričný klas",
            "sq" to "Misër",
            "sr" to "кукуруз",
            "sv" to "Majs",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Кукурудза",
            "vi" to "Bắp",
            "zh_Hans" to "玉米"
        )
    ),
    27 to Pair(
        "🍕",
        mapOf(
            "en" to "Pizza",
            "ar" to "بِيتزا",
            "bg" to "Пица",
            "ca" to "Pizza",
            "cs" to "Pizza",
            "de" to "Pizza",
            "eo" to "Pico",
            "es" to "Pizza",
            "et" to "Pitsa",
            "fi" to "Pizza",
            "fr" to "Pizza",
            "hr" to "pizza",
            "hu" to "Pizza",
            "id" to "Pizza",
            "it" to "Pizza",
            "ja" to "ピザ",
            "nb_NO" to "Pizza",
            "nl" to "Pizza",
            "pt_BR" to "Pizza",
            "ru" to "Пицца",
            "si" to "null",
            "sk" to "Pizza",
            "sq" to "Picë",
            "sr" to "пица",
            "sv" to "Pizza",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Піца",
            "vi" to "Pizza",
            "zh_Hans" to "披萨"
        )
    ),
    28 to Pair(
        "🎂",
        mapOf(
            "en" to "Cake",
            "ar" to "كَعكَة",
            "bg" to "Торта",
            "ca" to "Pastís",
            "cs" to "Dort",
            "de" to "Kuchen",
            "eo" to "Torto",
            "es" to "Tarta",
            "et" to "Kook",
            "fi" to "Kakku",
            "fr" to "Gâteau",
            "hr" to "torta",
            "hu" to "Süti",
            "id" to "Kue",
            "it" to "Torta",
            "ja" to "ケーキ",
            "nb_NO" to "Kake",
            "nl" to "Taart",
            "pt_BR" to "Bolo",
            "ru" to "Торт",
            "si" to "null",
            "sk" to "Narodeninová torta",
            "sq" to "Tortë",
            "sr" to "торта",
            "sv" to "Tårta",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Пиріг",
            "vi" to "Bánh",
            "zh_Hans" to "蛋糕"
        )
    ),
    29 to Pair(
        "❤",
        mapOf(
            "en" to "Heart",
            "ar" to "قَلب",
            "bg" to "Сърце",
            "ca" to "Cor",
            "cs" to "Srdce",
            "de" to "Herz",
            "eo" to "Koro",
            "es" to "Corazón",
            "et" to "Süda",
            "fi" to "Sydän",
            "fr" to "Cœur",
            "hr" to "srca",
            "hu" to "Szív",
            "id" to "Hati",
            "it" to "Cuore",
            "ja" to "ハート",
            "nb_NO" to "Hjerte",
            "nl" to "Hart",
            "pt_BR" to "Coração",
            "ru" to "Сердце",
            "si" to "null",
            "sk" to "červené srdce",
            "sq" to "Zemër",
            "sr" to "срце",
            "sv" to "Hjärta",
            "szl" to "null",
            "tzm" to "Ul",
            "uk" to "Серце",
            "vi" to "Tim",
            "zh_Hans" to "心"
        )
    ),
    30 to Pair(
        "😀",
        mapOf(
            "en" to "Smiley",
            "ar" to "اِبتِسَامَة",
            "bg" to "Усмивка",
            "ca" to "Somrient",
            "cs" to "Smajlík",
            "de" to "Lächeln",
            "eo" to "Rideto",
            "es" to "Emoticono",
            "et" to "Smaili",
            "fi" to "Hymynaama",
            "fr" to "Sourire",
            "hr" to "smajlića",
            "hu" to "Mosoly",
            "id" to "Senyuman",
            "it" to "Faccina sorridente",
            "ja" to "スマイル",
            "nb_NO" to "Smilefjes",
            "nl" to "Smiley",
            "pt_BR" to "Sorriso",
            "ru" to "Улыбка",
            "si" to "null",
            "sk" to "Škeriaca sa tvár",
            "sq" to "Emotikon",
            "sr" to "смајли",
            "sv" to "Smiley",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Посмішка",
            "vi" to "Mặt cười",
            "zh_Hans" to "笑脸"
        )
    ),
    31 to Pair(
        "🤖",
        mapOf(
            "en" to "Robot",
            "ar" to "رُوبُوت",
            "bg" to "Робот",
            "ca" to "Robot",
            "cs" to "Robot",
            "de" to "Roboter",
            "eo" to "Roboto",
            "es" to "Robot",
            "et" to "Robot",
            "fi" to "Robotti",
            "fr" to "Robot",
            "hr" to "robot",
            "hu" to "Robot",
            "id" to "Robot",
            "it" to "Robot",
            "ja" to "ロボと",
            "nb_NO" to "Robot",
            "nl" to "Robot",
            "pt_BR" to "Robô",
            "ru" to "Робот",
            "si" to "null",
            "sk" to "Robot",
            "sq" to "Robot",
            "sr" to "робот",
            "sv" to "Robot",
            "szl" to "null",
            "tzm" to "Aṛubu",
            "uk" to "Робот",
            "vi" to "Rô-bô",
            "zh_Hans" to "机器人"
        )
    ),
    32 to Pair(
        "🎩",
        mapOf(
            "en" to "Hat",
            "ar" to "قُبَّعَة",
            "bg" to "Шапка",
            "ca" to "Barret",
            "cs" to "Klobouk",
            "de" to "Hut",
            "eo" to "Ĉapelo",
            "es" to "Sombrero",
            "et" to "Kübar",
            "fi" to "Hattu",
            "fr" to "Chapeau",
            "hr" to "kapa",
            "hu" to "Kalap",
            "id" to "Topi",
            "it" to "Cappello",
            "ja" to "帽子",
            "nb_NO" to "Hatt",
            "nl" to "Hoed",
            "pt_BR" to "Chapéu",
            "ru" to "Шляпа",
            "si" to "null",
            "sk" to "Cilinder",
            "sq" to "Kapë",
            "sr" to "шешир",
            "sv" to "Hatt",
            "szl" to "null",
            "tzm" to "Taraza",
            "uk" to "Капелюх",
            "vi" to "Nón",
            "zh_Hans" to "帽子"
        )
    ),
    33 to Pair(
        "👓",
        mapOf(
            "en" to "Glasses",
            "ar" to "نَظَّارَة",
            "bg" to "Очила",
            "ca" to "Ulleres",
            "cs" to "Brýle",
            "de" to "Brille",
            "eo" to "Okulvitroj",
            "es" to "Gafas",
            "et" to "Prillid",
            "fi" to "Silmälasit",
            "fr" to "Lunettes",
            "hr" to "naočale",
            "hu" to "Szemüveg",
            "id" to "Kacamata",
            "it" to "Occhiali",
            "ja" to "めがね",
            "nb_NO" to "Briller",
            "nl" to "Bril",
            "pt_BR" to "Óculos",
            "ru" to "Очки",
            "si" to "null",
            "sk" to "Okuliare",
            "sq" to "Syze",
            "sr" to "наочаре",
            "sv" to "Glasögon",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Окуляри",
            "vi" to "Mắt kiếng",
            "zh_Hans" to "眼镜"
        )
    ),
    34 to Pair(
        "🔧",
        mapOf(
            "en" to "Spanner",
            "ar" to "مِفتَاحُ رَبط",
            "bg" to "Гаечен ключ",
            "ca" to "Clau anglesa",
            "cs" to "Klíč",
            "de" to "Schraubenschlüssel",
            "eo" to "Ŝraŭbŝlosilo",
            "es" to "Llave inglesa",
            "et" to "Mutrivõti",
            "fi" to "Kiintoavain",
            "fr" to "Clé à molette",
            "hr" to "ključ",
            "hu" to "Csavarkulcs",
            "id" to "Kunci Bengkel",
            "it" to "Chiave inglese",
            "ja" to "スパナ",
            "nb_NO" to "Fastnøkkel",
            "nl" to "Moersleutel",
            "pt_BR" to "Chave inglesa",
            "ru" to "Ключ",
            "si" to "null",
            "sk" to "Francúzsky kľúč",
            "sq" to "Çelës",
            "sr" to "кључ",
            "sv" to "Skruvnyckel",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Гайковий ключ",
            "vi" to "Cờ-lê",
            "zh_Hans" to "扳手"
        )
    ),
    35 to Pair(
        "🎅",
        mapOf(
            "en" to "Santa",
            "ar" to "سانتا",
            "bg" to "Дядо Коледа",
            "ca" to "Pare Noél",
            "cs" to "Mikuláš",
            "de" to "Weihnachtsmann",
            "eo" to "Kristnaska viro",
            "es" to "Papá Noel",
            "et" to "Jõuluvana",
            "fi" to "Joulupukki",
            "fr" to "Père Noël",
            "hr" to "deda Mraz",
            "hu" to "Télapó",
            "id" to "Santa",
            "it" to "Babbo Natale",
            "ja" to "サンタ",
            "nb_NO" to "Julenisse",
            "nl" to "Kerstman",
            "pt_BR" to "Papai-noel",
            "ru" to "Санта",
            "si" to "null",
            "sk" to "Santa Claus",
            "sq" to "Babagjyshi i Vitit të Ri",
            "sr" to "деда Мраз",
            "sv" to "Tomte",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Санта Клаус",
            "vi" to "ông già Noel",
            "zh_Hans" to "圣诞老人"
        )
    ),
    36 to Pair(
        "👍",
        mapOf(
            "en" to "Thumbs Up",
            "ar" to "رَفعُ إِبهَام",
            "bg" to "Палец нагоре",
            "ca" to "Polzes amunt",
            "cs" to "Palec nahoru",
            "de" to "Daumen Hoch",
            "eo" to "Dikfingro supren",
            "es" to "Pulgar arriba",
            "et" to "Pöidlad püsti",
            "fi" to "Peukalo ylös",
            "fr" to "Pouce en l’air",
            "hr" to "palac gore",
            "hu" to "Hüvelykujj fel",
            "id" to "Jempol",
            "it" to "Pollice alzato",
            "ja" to "いいね",
            "nb_NO" to "Tommel Opp",
            "nl" to "Duim omhoog",
            "pt_BR" to "Joinha",
            "ru" to "Большой палец вверх",
            "si" to "null",
            "sk" to "Palec nahor",
            "sq" to "null",
            "sr" to "палчић горе",
            "sv" to "Tummen upp",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Великий палець вгору",
            "vi" to "Thích",
            "zh_Hans" to "赞"
        )
    ),
    37 to Pair(
        "☂️",
        mapOf(
            "en" to "Umbrella",
            "ar" to "مِظَلَّة",
            "bg" to "Чадър",
            "ca" to "Paraigües",
            "cs" to "Deštník",
            "de" to "Regenschirm",
            "eo" to "Ombrelo",
            "es" to "Paraguas",
            "et" to "Vihmavari",
            "fi" to "Sateenvarjo",
            "fr" to "Parapluie",
            "hr" to "kišobran",
            "hu" to "Esernyő",
            "id" to "Payung",
            "it" to "Ombrello",
            "ja" to "傘",
            "nb_NO" to "Paraply",
            "nl" to "Paraplu",
            "pt_BR" to "Guarda-chuva",
            "ru" to "Зонт",
            "si" to "null",
            "sk" to "Dáždnik",
            "sq" to "Ombrellë",
            "sr" to "кишобран",
            "sv" to "Paraply",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Парасолька",
            "vi" to "Cây dù",
            "zh_Hans" to "伞"
        )
    ),
    38 to Pair(
        "⌛",
        mapOf(
            "en" to "Hourglass",
            "ar" to "سَاعَةٌ رَملِيَّة",
            "bg" to "Пясъчен часовник",
            "ca" to "Rellotge de sorra",
            "cs" to "Přesýpací hodiny",
            "de" to "Sanduhr",
            "eo" to "Sablohorloĝo",
            "es" to "Reloj de arena",
            "et" to "Liivakell",
            "fi" to "Tiimalasi",
            "fr" to "Sablier",
            "hr" to "pješčani sat",
            "hu" to "Homokóra",
            "id" to "Jam Pasir",
            "it" to "Clessidra",
            "ja" to "砂時計",
            "nb_NO" to "Timeglass",
            "nl" to "Zandloper",
            "pt_BR" to "Ampulheta",
            "ru" to "Песочные часы",
            "si" to "null",
            "sk" to "Presýpacie hodiny",
            "sq" to "Klepsidër",
            "sr" to "пешчаник",
            "sv" to "Timglas",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Пісковий годинник",
            "vi" to "Đồng hồ cát",
            "zh_Hans" to "沙漏"
        )
    ),
    39 to Pair(
        "⏰",
        mapOf(
            "en" to "Clock",
            "ar" to "سَاعَة",
            "bg" to "Часовник",
            "ca" to "Rellotge",
            "cs" to "Hodiny",
            "de" to "Uhr",
            "eo" to "Horloĝo",
            "es" to "Reloj",
            "et" to "Kell",
            "fi" to "Pöytäkello",
            "fr" to "Réveil",
            "hr" to "sat",
            "hu" to "Óra",
            "id" to "Jam",
            "it" to "Orologio",
            "ja" to "時計",
            "nb_NO" to "Klokke",
            "nl" to "Wekker",
            "pt_BR" to "Relógio",
            "ru" to "Часы",
            "si" to "null",
            "sk" to "Budík",
            "sq" to "Sahat",
            "sr" to "сат",
            "sv" to "Klocka",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Годинник",
            "vi" to "Đồng hồ",
            "zh_Hans" to "时钟"
        )
    ),
    40 to Pair(
        "🎁",
        mapOf(
            "en" to "Gift",
            "ar" to "هَدِيَّة",
            "bg" to "Подарък",
            "ca" to "Regal",
            "cs" to "Dárek",
            "de" to "Geschenk",
            "eo" to "Donaco",
            "es" to "Regalo",
            "et" to "Kingitus",
            "fi" to "Lahja",
            "fr" to "Cadeau",
            "hr" to "poklon",
            "hu" to "Ajándék",
            "id" to "Kado",
            "it" to "Regalo",
            "ja" to "ギフト",
            "nb_NO" to "Gave",
            "nl" to "Geschenk",
            "pt_BR" to "Presente",
            "ru" to "Подарок",
            "si" to "null",
            "sk" to "Zabalený darček",
            "sq" to "Dhuratë",
            "sr" to "поклон",
            "sv" to "Present",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Подарунок",
            "vi" to "Quà",
            "zh_Hans" to "礼物"
        )
    ),
    41 to Pair(
        "💡",
        mapOf(
            "en" to "Light Bulb",
            "ar" to "مِصبَاح",
            "bg" to "Лампа",
            "ca" to "Bombeta",
            "cs" to "Žárovka",
            "de" to "Glühbirne",
            "eo" to "Lampo",
            "es" to "Bombilla",
            "et" to "Lambipirn",
            "fi" to "Hehkulamppu",
            "fr" to "Ampoule",
            "hr" to "žarulja",
            "hu" to "Égő",
            "id" to "Bohlam Lampu",
            "it" to "Lampadina",
            "ja" to "電球",
            "nb_NO" to "Lyspære",
            "nl" to "Gloeilamp",
            "pt_BR" to "Lâmpada",
            "ru" to "Лампочка",
            "si" to "null",
            "sk" to "Žiarovka",
            "sq" to "Llambë",
            "sr" to "сијалица",
            "sv" to "Lampa",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Лампочка",
            "vi" to "Bóng đèn tròn",
            "zh_Hans" to "灯泡"
        )
    ),
    42 to Pair(
        "📕",
        mapOf(
            "en" to "Book",
            "ar" to "كِتَاب",
            "bg" to "Книга",
            "ca" to "Llibre",
            "cs" to "Kniha",
            "de" to "Buch",
            "eo" to "Libro",
            "es" to "Libro",
            "et" to "Raamat",
            "fi" to "Kirja",
            "fr" to "Livre",
            "hr" to "knjiga",
            "hu" to "Könyv",
            "id" to "Buku",
            "it" to "Libro",
            "ja" to "本",
            "nb_NO" to "Bok",
            "nl" to "Boek",
            "pt_BR" to "Livro",
            "ru" to "Книга",
            "si" to "null",
            "sk" to "Zatvorená kniha",
            "sq" to "Libër",
            "sr" to "књига",
            "sv" to "Bok",
            "szl" to "null",
            "tzm" to "Adlis",
            "uk" to "Книга",
            "vi" to "Sách",
            "zh_Hans" to "书"
        )
    ),
    43 to Pair(
        "✏️",
        mapOf(
            "en" to "Pencil",
            "ar" to "قَلَمُ رَصاص",
            "bg" to "Молив",
            "ca" to "Llapis",
            "cs" to "Tužka",
            "de" to "Bleistift",
            "eo" to "Krajono",
            "es" to "Lápiz",
            "et" to "Pliiats",
            "fi" to "Lyijykynä",
            "fr" to "Crayon",
            "hr" to "olovka",
            "hu" to "Ceruza",
            "id" to "Pensil",
            "it" to "Matita",
            "ja" to "鉛筆",
            "nb_NO" to "Blyant",
            "nl" to "Potlood",
            "pt_BR" to "Lápis",
            "ru" to "Карандаш",
            "si" to "null",
            "sk" to "Ceruzka",
            "sq" to "Laps",
            "sr" to "оловка",
            "sv" to "Penna",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Олівець",
            "vi" to "Viết chì",
            "zh_Hans" to "铅笔"
        )
    ),
    44 to Pair(
        "📎",
        mapOf(
            "en" to "Paperclip",
            "ar" to "مِشبَكُ وَرَق",
            "bg" to "Кламер",
            "ca" to "Clip",
            "cs" to "Sponka",
            "de" to "Büroklammer",
            "eo" to "Paperkuntenilo",
            "es" to "Clip",
            "et" to "Kirjaklamber",
            "fi" to "Paperiliitin",
            "fr" to "Trombone",
            "hr" to "spajalica",
            "hu" to "Gémkapocs",
            "id" to "Klip Kertas",
            "it" to "Graffetta",
            "ja" to "クリップ",
            "nb_NO" to "BInders",
            "nl" to "Papierklemmetje",
            "pt_BR" to "Clipe de papel",
            "ru" to "Скрепка",
            "si" to "null",
            "sk" to "Sponka na papier",
            "sq" to "Kapëse",
            "sr" to "спајалица",
            "sv" to "Gem",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Спиначка",
            "vi" to "Kẹp giấy",
            "zh_Hans" to "回形针"
        )
    ),
    45 to Pair(
        "✂️",
        mapOf(
            "en" to "Scissors",
            "ar" to "مِقَصّ",
            "bg" to "Ножици",
            "ca" to "Tisores",
            "cs" to "Nůžky",
            "de" to "Schere",
            "eo" to "Tondilo",
            "es" to "Tijeras",
            "et" to "Käärid",
            "fi" to "Sakset",
            "fr" to "Ciseaux",
            "hr" to "škare",
            "hu" to "Olló",
            "id" to "Gunting",
            "it" to "Forbici",
            "ja" to "はさみ",
            "nb_NO" to "Saks",
            "nl" to "Schaar",
            "pt_BR" to "Tesoura",
            "ru" to "Ножницы",
            "si" to "null",
            "sk" to "Nožnice",
            "sq" to "Gërshërë",
            "sr" to "маказе",
            "sv" to "Sax",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Ножиці",
            "vi" to "Cây kéo",
            "zh_Hans" to "剪刀"
        )
    ),
    46 to Pair(
        "🔒",
        mapOf(
            "en" to "Lock",
            "ar" to "قُفل",
            "bg" to "Катинар",
            "ca" to "Cadenat",
            "cs" to "Zámek",
            "de" to "Schloss",
            "eo" to "Seruro",
            "es" to "Candado",
            "et" to "Lukk",
            "fi" to "Lukko",
            "fr" to "Cadenas",
            "hr" to "zaključati",
            "hu" to "Lakat",
            "id" to "Gembok",
            "it" to "Lucchetto",
            "ja" to "錠前",
            "nb_NO" to "Lås",
            "nl" to "Slot",
            "pt_BR" to "Cadeado",
            "ru" to "Замок",
            "si" to "null",
            "sk" to "Zatvorená zámka",
            "sq" to "Dry",
            "sr" to "катанац",
            "sv" to "Lås",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Замок",
            "vi" to "Ổ khóa",
            "zh_Hans" to "锁"
        )
    ),
    47 to Pair(
        "🔑",
        mapOf(
            "en" to "Key",
            "ar" to "مِفتَاح",
            "bg" to "Ключ",
            "ca" to "Clau",
            "cs" to "Klíč",
            "de" to "Schlüssel",
            "eo" to "Ŝlosilo",
            "es" to "Llave",
            "et" to "Võti",
            "fi" to "Avain",
            "fr" to "Clé",
            "hr" to "ključ",
            "hu" to "Kulcs",
            "id" to "Kunci",
            "it" to "Chiave",
            "ja" to "鍵",
            "nb_NO" to "Nøkkel",
            "nl" to "Sleutel",
            "pt_BR" to "Chave",
            "ru" to "Ключ",
            "si" to "null",
            "sk" to "Kľúč",
            "sq" to "Çelës",
            "sr" to "кључ",
            "sv" to "Nyckel",
            "szl" to "null",
            "tzm" to "Tasarut",
            "uk" to "Ключ",
            "vi" to "Chìa khóa",
            "zh_Hans" to "钥匙"
        )
    ),
    48 to Pair(
        "🔨",
        mapOf(
            "en" to "Hammer",
            "ar" to "مِطرَقَة",
            "bg" to "Чук",
            "ca" to "Martell",
            "cs" to "Kladivo",
            "de" to "Hammer",
            "eo" to "Martelo",
            "es" to "Martillo",
            "et" to "Haamer",
            "fi" to "Vasara",
            "fr" to "Marteau",
            "hr" to "čekić",
            "hu" to "Kalapács",
            "id" to "Palu",
            "it" to "Martello",
            "ja" to "金槌",
            "nb_NO" to "Hammer",
            "nl" to "Hamer",
            "pt_BR" to "Martelo",
            "ru" to "Молоток",
            "si" to "null",
            "sk" to "Kladivo",
            "sq" to "Çekiç",
            "sr" to "чекић",
            "sv" to "Hammare",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Молоток",
            "vi" to "Búa",
            "zh_Hans" to "锤子"
        )
    ),
    49 to Pair(
        "☎️",
        mapOf(
            "en" to "Telephone",
            "ar" to "تِلِفُون",
            "bg" to "Телефон",
            "ca" to "Telèfon",
            "cs" to "Telefon",
            "de" to "Telefon",
            "eo" to "Telefono",
            "es" to "Telefono",
            "et" to "Telefon",
            "fi" to "Puhelin",
            "fr" to "Téléphone",
            "hr" to "telefon",
            "hu" to "Telefon",
            "id" to "Telepon",
            "it" to "Telefono",
            "ja" to "電話機",
            "nb_NO" to "Telefon",
            "nl" to "Telefoon",
            "pt_BR" to "Telefone",
            "ru" to "Телефон",
            "si" to "null",
            "sk" to "Telefón",
            "sq" to "Telefon",
            "sr" to "телефон",
            "sv" to "Telefon",
            "szl" to "null",
            "tzm" to "Atilifun",
            "uk" to "Телефон",
            "vi" to "Điện thoại",
            "zh_Hans" to "电话"
        )
    ),
    50 to Pair(
        "🏁",
        mapOf(
            "en" to "Flag",
            "ar" to "عَلَم",
            "bg" to "Флаг",
            "ca" to "Bandera",
            "cs" to "Vlajka",
            "de" to "Flagge",
            "eo" to "Flago",
            "es" to "Bandera",
            "et" to "Lipp",
            "fi" to "Lippu",
            "fr" to "Drapeau",
            "hr" to "zastava",
            "hu" to "Zászló",
            "id" to "Bendera",
            "it" to "Bandiera",
            "ja" to "旗",
            "nb_NO" to "Flagg",
            "nl" to "Vlag",
            "pt_BR" to "Bandeira",
            "ru" to "Флаг",
            "si" to "null",
            "sk" to "Kockovaná zástava",
            "sq" to "Flamur",
            "sr" to "застава",
            "sv" to "Flagga",
            "szl" to "null",
            "tzm" to "Acenyal",
            "uk" to "Прапор",
            "vi" to "Lá cờ",
            "zh_Hans" to "旗帜"
        )
    ),
    51 to Pair(
        "🚂",
        mapOf(
            "en" to "Train",
            "ar" to "قِطَار",
            "bg" to "Влак",
            "ca" to "Tren",
            "cs" to "Vlak",
            "de" to "Zug",
            "eo" to "Vagonaro",
            "es" to "Tren",
            "et" to "Rong",
            "fi" to "Juna",
            "fr" to "Train",
            "hr" to "vlak",
            "hu" to "Vonat",
            "id" to "Kereta Api",
            "it" to "Treno",
            "ja" to "電車",
            "nb_NO" to "Tog",
            "nl" to "Trein",
            "pt_BR" to "Trem",
            "ru" to "Поезд",
            "si" to "null",
            "sk" to "Rušeň",
            "sq" to "Tren",
            "sr" to "воз",
            "sv" to "Tåg",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Потяг",
            "vi" to "Xe lửa",
            "zh_Hans" to "火车"
        )
    ),
    52 to Pair(
        "🚲",
        mapOf(
            "en" to "Bicycle",
            "ar" to "دَرّاجَة",
            "bg" to "Колело",
            "ca" to "Bicicleta",
            "cs" to "Kolo",
            "de" to "Fahrrad",
            "eo" to "Biciklo",
            "es" to "Bicicleta",
            "et" to "Jalgratas",
            "fi" to "Polkupyörä",
            "fr" to "Vélo",
            "hr" to "bicikl",
            "hu" to "Kerékpár",
            "id" to "Sepeda",
            "it" to "Bicicletta",
            "ja" to "自転車",
            "nb_NO" to "Sykkel",
            "nl" to "Fiets",
            "pt_BR" to "Bicicleta",
            "ru" to "Велосипед",
            "si" to "null",
            "sk" to "Bicykel",
            "sq" to "Biçikletë",
            "sr" to "бицикл",
            "sv" to "Cykel",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Велосипед",
            "vi" to "Xe đạp",
            "zh_Hans" to "自行车"
        )
    ),
    53 to Pair(
        "✈️",
        mapOf(
            "en" to "Aeroplane",
            "ar" to "طَائِرة",
            "bg" to "Самолет",
            "ca" to "Avió",
            "cs" to "Letadlo",
            "de" to "Flugzeug",
            "eo" to "Aviadilo",
            "es" to "Avión",
            "et" to "Lennuk",
            "fi" to "Lentokone",
            "fr" to "Avion",
            "hr" to "avion",
            "hu" to "Repülő",
            "id" to "Pesawat",
            "it" to "Aeroplano",
            "ja" to "飛行機",
            "nb_NO" to "Fly",
            "nl" to "Vliegtuig",
            "pt_BR" to "Avião",
            "ru" to "Самолет",
            "si" to "null",
            "sk" to "Lietadlo",
            "sq" to "Avion",
            "sr" to "авион",
            "sv" to "Flygplan",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Літак",
            "vi" to "Máy bay",
            "zh_Hans" to "飞机"
        )
    ),
    54 to Pair(
        "🚀",
        mapOf(
            "en" to "Rocket",
            "ar" to "صَارُوخ",
            "bg" to "Ракета",
            "ca" to "Coet",
            "cs" to "Raketa",
            "de" to "Rakete",
            "eo" to "Raketo",
            "es" to "Cohete",
            "et" to "Rakett",
            "fi" to "Raketti",
            "fr" to "Fusée",
            "hr" to "raketa",
            "hu" to "Rakáta",
            "id" to "Roket",
            "it" to "Razzo",
            "ja" to "ロケット",
            "nb_NO" to "Rakett",
            "nl" to "Raket",
            "pt_BR" to "Foguete",
            "ru" to "Ракета",
            "si" to "null",
            "sk" to "Raketa",
            "sq" to "Raketë",
            "sr" to "ракета",
            "sv" to "Raket",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Ракета",
            "vi" to "Tên lửa",
            "zh_Hans" to "火箭"
        )
    ),
    55 to Pair(
        "🏆",
        mapOf(
            "en" to "Trophy",
            "ar" to "كَأسُ النَّصر",
            "bg" to "Трофей",
            "ca" to "Trofeu",
            "cs" to "Pohár",
            "de" to "Pokal",
            "eo" to "Trofeo",
            "es" to "Trofeo",
            "et" to "Auhind",
            "fi" to "Palkinto",
            "fr" to "Trophée",
            "hr" to "trofej",
            "hu" to "Trófea",
            "id" to "Piala",
            "it" to "Trofeo",
            "ja" to "トロフィー",
            "nb_NO" to "Pokal",
            "nl" to "Trofee",
            "pt_BR" to "Troféu",
            "ru" to "Кубок",
            "si" to "null",
            "sk" to "Trofej",
            "sq" to "Trofe",
            "sr" to "пехар",
            "sv" to "Trofé",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Приз",
            "vi" to "Cúp",
            "zh_Hans" to "奖杯"
        )
    ),
    56 to Pair(
        "⚽",
        mapOf(
            "en" to "Ball",
            "ar" to "كُرَة",
            "bg" to "Топка",
            "ca" to "Pilota",
            "cs" to "Míč",
            "de" to "Ball",
            "eo" to "Pilko",
            "es" to "Bola",
            "et" to "Pall",
            "fi" to "Pallo",
            "fr" to "Ballon",
            "hr" to "lopta",
            "hu" to "Labda",
            "id" to "Bola",
            "it" to "Palla",
            "ja" to "ボール",
            "nb_NO" to "Ball",
            "nl" to "Bal",
            "pt_BR" to "Bola",
            "ru" to "Мяч",
            "si" to "null",
            "sk" to "Futbal",
            "sq" to "Top",
            "sr" to "лопта",
            "sv" to "Boll",
            "szl" to "null",
            "tzm" to "Tcama",
            "uk" to "М'яч",
            "vi" to "Banh",
            "zh_Hans" to "球"
        )
    ),
    57 to Pair(
        "🎸",
        mapOf(
            "en" to "Guitar",
            "ar" to "غيتار",
            "bg" to "Китара",
            "ca" to "Guitarra",
            "cs" to "Kytara",
            "de" to "Gitarre",
            "eo" to "Gitaro",
            "es" to "Guitarra",
            "et" to "Kitarr",
            "fi" to "Kitara",
            "fr" to "Guitare",
            "hr" to "gitara",
            "hu" to "Gitár",
            "id" to "Gitar",
            "it" to "Chitarra",
            "ja" to "ギター",
            "nb_NO" to "Gitar",
            "nl" to "Gitaar",
            "pt_BR" to "Guitarra",
            "ru" to "Гитара",
            "si" to "null",
            "sk" to "Gitara",
            "sq" to "Kitarë",
            "sr" to "гитара",
            "sv" to "Gitarr",
            "szl" to "null",
            "tzm" to "Agiṭaṛ",
            "uk" to "Гітара",
            "vi" to "Ghi-ta",
            "zh_Hans" to "吉他"
        )
    ),
    58 to Pair(
        "🎺",
        mapOf(
            "en" to "Trumpet",
            "ar" to "بُوق",
            "bg" to "Тромпет",
            "ca" to "Trompeta",
            "cs" to "Trumpeta",
            "de" to "Trompete",
            "eo" to "Trumpeto",
            "es" to "Trompeta",
            "et" to "Trompet",
            "fi" to "Trumpetti",
            "fr" to "Trompette",
            "hr" to "truba",
            "hu" to "Trombita",
            "id" to "Terompet",
            "it" to "Trombetta",
            "ja" to "トランペット",
            "nb_NO" to "Trompet",
            "nl" to "Trompet",
            "pt_BR" to "Trombeta",
            "ru" to "Труба",
            "si" to "null",
            "sk" to "Trúbka",
            "sq" to "Trombë",
            "sr" to "труба",
            "sv" to "Trumpet",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Труба",
            "vi" to "Kèn",
            "zh_Hans" to "喇叭"
        )
    ),
    59 to Pair(
        "🔔",
        mapOf(
            "en" to "Bell",
            "ar" to "جَرَس",
            "bg" to "Звънец",
            "ca" to "Campana",
            "cs" to "Zvonek",
            "de" to "Glocke",
            "eo" to "Sonorilo",
            "es" to "Campana",
            "et" to "Kelluke",
            "fi" to "Soittokello",
            "fr" to "Cloche",
            "hr" to "zvono",
            "hu" to "Harang",
            "id" to "Lonceng",
            "it" to "Campana",
            "ja" to "ベル",
            "nb_NO" to "Bjelle",
            "nl" to "Bel",
            "pt_BR" to "Sino",
            "ru" to "Колокол",
            "si" to "null",
            "sk" to "Zvon",
            "sq" to "Kambanë",
            "sr" to "звоно",
            "sv" to "Bjällra",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Дзвін",
            "vi" to "Chuông",
            "zh_Hans" to "铃铛"
        )
    ),
    60 to Pair(
        "⚓",
        mapOf(
            "en" to "Anchor",
            "ar" to "مِرسَاة",
            "bg" to "Котва",
            "ca" to "Àncora",
            "cs" to "Kotva",
            "de" to "Anker",
            "eo" to "Ankro",
            "es" to "Ancla",
            "et" to "Ankur",
            "fi" to "Ankkuri",
            "fr" to "Ancre",
            "hr" to "sidro",
            "hu" to "Horgony",
            "id" to "Jangkar",
            "it" to "Ancora",
            "ja" to "いかり",
            "nb_NO" to "Anker",
            "nl" to "Anker",
            "pt_BR" to "Âncora",
            "ru" to "Якорь",
            "si" to "null",
            "sk" to "Kotva",
            "sq" to "Spirancë",
            "sr" to "сидро",
            "sv" to "Ankare",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Якір",
            "vi" to "Mỏ neo",
            "zh_Hans" to "锚"
        )
    ),
    61 to Pair(
        "🎧",
        mapOf(
            "en" to "Headphones",
            "ar" to "سَمّاعَة رَأس",
            "bg" to "Слушалки",
            "ca" to "Auriculars",
            "cs" to "Sluchátka",
            "de" to "Kopfhörer",
            "eo" to "Kapaŭdilo",
            "es" to "Cascos",
            "et" to "Kõrvaklapid",
            "fi" to "Kuulokkeet",
            "fr" to "Casque audio",
            "hr" to "slušalice",
            "hu" to "Fejhallgató",
            "id" to "Headphone",
            "it" to "Cuffie",
            "ja" to "ヘッドホン",
            "nb_NO" to "Hodetelefoner",
            "nl" to "Koptelefoon",
            "pt_BR" to "Fones de ouvido",
            "ru" to "Наушники",
            "si" to "null",
            "sk" to "Slúchadlá",
            "sq" to "Kufje",
            "sr" to "слушалице",
            "sv" to "Hörlurar",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Навушники",
            "vi" to "Tai nghe",
            "zh_Hans" to "耳机"
        )
    ),
    62 to Pair(
        "📁",
        mapOf(
            "en" to "Folder",
            "ar" to "مُجَلَّد",
            "bg" to "Папка",
            "ca" to "Carpeta",
            "cs" to "Složka",
            "de" to "Ordner",
            "eo" to "Dosierujo",
            "es" to "Carpeta",
            "et" to "Kaust",
            "fi" to "Kansio",
            "fr" to "Dossier",
            "hr" to "mapu",
            "hu" to "Mappa",
            "id" to "Map",
            "it" to "Cartella",
            "ja" to "フォルダ",
            "nb_NO" to "Mappe",
            "nl" to "Map",
            "pt_BR" to "Pasta",
            "ru" to "Папка",
            "si" to "null",
            "sk" to "Fascikel",
            "sq" to "Dosje",
            "sr" to "фасцикла",
            "sv" to "Mapp",
            "szl" to "null",
            "tzm" to "Asdaw",
            "uk" to "Тека",
            "vi" to "Thư mục",
            "zh_Hans" to "文件夹"
        )
    ),
    63 to Pair(
        "📌",
        mapOf(
            "en" to "Pin",
            "ar" to "دَبُّوس",
            "bg" to "Кабърче",
            "ca" to "Xinxeta",
            "cs" to "Špendlík",
            "de" to "Stecknadel",
            "eo" to "Pinglo",
            "es" to "Alfiler",
            "et" to "Nööpnõel",
            "fi" to "Nuppineula",
            "fr" to "Punaise",
            "hr" to "pribadača",
            "hu" to "Rajszeg",
            "id" to "Pin",
            "it" to "Puntina",
            "ja" to "ピン",
            "nb_NO" to "Tegnestift",
            "nl" to "Duimspijker",
            "pt_BR" to "Alfinete",
            "ru" to "Булавка",
            "si" to "null",
            "sk" to "Špendlík",
            "sq" to "Karficë",
            "sr" to "чиода",
            "sv" to "Häftstift",
            "szl" to "null",
            "tzm" to "null",
            "uk" to "Кнопка",
            "vi" to "Ghim",
            "zh_Hans" to "图钉"
        )
    )
)